osx_image: xcode9
language: objective-c
cache:
  - bundler
  - cocoapods
branches:
  only:
    - develop
    - master
    - patch
notifications:
  email: false
  slack: projetchaos-esgi:KFVAv8xsSyzpX0POOYdEbiJ9
before_install:
  - gem install bundler
  - gem update fastlane
script: bundle exec fastlane toasty
