osx_image: xcode9
language: objective-c
cache:
  - bundler
  - cocoapods
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - gem update fastlane
  - brew update
  - bundle install
script: bundle exec fastlane toasty_deploy
