lane :toasty do
  scan
  if git_branch() == "master"
    toasty_deploy
  end
  if git_branch() == "patch"
    toasty_patched
  end
end

lane :toasty_deploy do
    #version = get_version_number()

    update_app_identifier(
      plist_path: "Toasty/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: "com.alkrox.Toasty"
    )
    #version = increment_version_number(
    #  bump_type: "minor"
    #)


    #version = increment_version_number(
    #  bump_type: "minor" # Automatically increment minor version number
    #)

    set_github_release(
      repository_name: "sereytraing/toasty",
      name: version,
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: "Test Toasty",
      commitish: "master"
    )
    version_bump_podspec(path: "Toasty_MVS.podspec", bump_type: "minor")
    #pod_push
end

lane :toasty_patched do
  version = get_version_number()
  version = increment_version_number(
    bump_type: "patch"
  )
  version_bump_podspec(path: "Toasty_MVS.podspec", bump_type: "patch")
end

lane :toasty_noretrovers do
  version = get_version_number()
  version = increment_version_number(
    bump_type: "major"
  )
end
