before_all do
  ensure_git_status_clean
end

lane :toasty do
  scan
  if git_branch() == "master"
    toasty_deploy_travis
  end
end

lane :toasty_deploy_minor do
    version = get_version_number()

    version = increment_version_number(
      bump_type: "minor"
    )

    version_bump_podspec(path: "Toasty_MVS.podspec", bump_type: "minor")

    push_to_git_remote(
      remote: "origin",
      local_branch: "develop",
      remote_branch: "master",
      force: true,
      tags: false
    )
end

lane :toasty_deploy_patch do
    version = get_version_number()

    version = increment_version_number(
      bump_type: "patch"
    )

    version_bump_podspec(path: "Toasty_MVS.podspec", bump_type: "patch")

    push_to_git_remote(
      remote: "origin",
      local_branch: "patch",
      remote_branch: "master",
      force: true,
      tags: false
    )
end

lane :toasty_deploy_travis do
  set_github_release(
    repository_name: "sereytraing/toasty",
    name: version,
    tag_name: "v#{version}",
    api_token: ENV["GITHUB_TOKEN"],
    description: "Test Toasty",
    commitish: "master"
  )

  pod_push
end
