lane :toastyTest do
  #scan(
  #  code_coverage: true,
  #  open_report: true
  #)
  scan
  if git_branch() == "master"
    toasty_deploy
  end
  if git_branch() == "develop"
  end
end

lane :toasty_deploy do
    version = get_version_number()
    version = increment_version_number(
      bump_type: "minor" # Automatically increment minor version number
    )
    set_github_release(
      repository_name: "sereytraing/toasty",
      name: version,
      tag_name: "v#{version}",
      api_token: "973668646a45d31de636566a16daae370d0d0bca",
      description: "Test Toasty",
      commitish: "master"
    )
end
